version: '3'
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
  app:
    build: .
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - cassandra
    environment:
      - DBPORT=9042
      - DB=cassandra
volumes:
  cassandra: